### ISSUE TITLE
The issue of incomplete window display in GUI

### ISSUE THREAD

**Issue by b224hisl** [Nubis-Communications/SignalIntegrity#77]
When I install software on a Linux server and use VNC Viewer to display the graphical interface, I notice that the window display is not complete, as indicated by the markings in the screenshot below. There is also no scrollbar nearby to scroll through the window. How should I handle this situation?
![image](https://github.com/Nubis-Communications/SignalIntegrity/assets/39954153/b2eee670-a30b-4371-bd40-6f83504c9323)

**Comment by PetePupalaikis** [comment]
It looks to me like the screen resolution and size for your VNC viewer is too small.  Can this size be defined by you (i.e. make the screen bigger).  This is the problem I see if I change one of my screens to a ridiculously small size like 800 x 600 on my laptop: 
![image](https://github.com/Nubis-Communications/SignalIntegrity/assets/16583311/204f75f5-9c74-4d1c-8783-f86ec8487c02)
I can change the default size using the preferences:
![image](https://github.com/Nubis-Communications/SignalIntegrity/assets/16583311/ffbc3ff8-47b1-4f1b-b916-c0fb7ca72438)
In which I can now get this:
![image](https://github.com/Nubis-Communications/SignalIntegrity/assets/16583311/c822d142-e7e0-4297-9a79-35a83c59a051)
But the better idea would be to increase the size of your screen and resolution for your VNC viewer.
Good luck.

**Comment by b224hisl** [comment]
OK thank you very much! I have solved this problem
