### ISSUE TITLE
How to save the s-parameter file

### ISSUE THREAD

**Issue by b224hisl** [Nubis-Communications/SignalIntegrity#78]
Excuse me, 
When I get my s-parameter, I click 'File-> save' then I can save a ".s2p" file, as shown here:
![image](https://github.com/Nubis-Communications/SignalIntegrity/assets/39954153/77a068da-37f8-4a73-821d-f746943df82d)
But when I load this ".s2p" file by click 'File - > Open File' then I open the s2p file I just generated, it seems that I don't save this the s-parameter successfully. As shown here:
![image](https://github.com/Nubis-Communications/SignalIntegrity/assets/39954153/a7d576b5-33e0-4842-9345-31742ddc8b5c)
Nothing is shown in the latter diagram. Do you know what happen?

**Comment by PetePupalaikis** [comment]
Generally, SignalIntgetrity saves s-parameters with six digits of precison.  This can be changed in your Help->Preferences:
![image](https://github.com/Nubis-Communications/SignalIntegrity/assets/16583311/39546f8c-c0f2-4105-af8a-a7e6c2e06b2d)

It looks to me like maybe you just need more precision in saving.  -52 dB return loss is pretty low for signal integrity applications, so if it is not saved with high enough precision, it will round them down to zero.  Also, you can open the touchstone file (the .s2p file) in an editor and take a look.  It should look like this:

! File created by SignalIntegrity v1.4.2: Signal and Power Integrity Tools
! https://github.com/Nubis-Communications/SignalIntegrity
# MHz S MA R 50.0
0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0
10.0 1.255e-06 89.963999928 1.0 -0.036000072 1.0 -0.036000072 1.255e-06 89.963999928
20.0 2.511e-06 89.927999856 1.0 -0.072000144 1.0 -0.072000144 2.511e-06 89.927999856
30.0 3.766e-06 89.891999784 1.0 -0.108000216 1.0 -0.108000216 3.766e-06 89.891999784
40.0 5.022e-06 89.855999713 1.0 -0.144000287 1.0 -0.144000287 5.022e-06 89.855999713
50.0 6.277e-06 89.819999641 1.0 -0.180000359 1.0 -0.180000359 6.277e-06 89.819999641
60.0 7.532e-06 89.783999569 1.0 -0.216000431 1.0 -0.216000431 7.532e-06 89.783999569
70.0 8.788e-06 89.747999497 1.0 -0.252000503 1.0 -0.252000503 8.788e-06 89.747999497
80.0 1.0043e-05 89.711999425 1.0 -0.288000575 1.0 -0.288000575 1.0043e-05 89.711999425
90.0 1.1298e-05 89.675999353 1.0 -0.324000647 1.0 -0.324000647 1.1298e-05 89.675999353
100.0 1.2554e-05 89.639999281 1.0 -0.360000719 1.0 -0.360000719 1.2554e-05 89.639999281
110.0 1.3809e-05 89.60399921 1.0 -0.39600079 1.0 -0.39600079 1.3809e-05 89.60399921
120.0 1.5064e-05 89.567999138 1.0 -0.432000862 1.0 -0.432000862 1.5064e-05 89.567999138
130.0 1.632e-05 89.531999066 1.0 -0.468000934 1.0 -0.468000934 1.632e-05 89.531999066
140.0 1.7575e-05 89.495998994 1.0 -0.504001006 1.0 -0.504001006 1.7575e-05 89.495998994
150.0 1.883e-05 89.459998922 1.0 -0.540001078 1.0 -0.540001078 1.883e-05 89.459998922
160.0 2.0086e-05 89.42399885 1.0 -0.57600115 1.0 -0.57600115 2.0086e-05 89.42399885
170.0 2.1341e-05 89.387998779 1.0 -0.612001221 1.0 -0.612001221 2.1341e-05 89.387998779
180.0 2.2596e-05 89.351998707 1.0 -0.648001293 1.0 -0.648001293 2.2596e-05 89.351998707
190.0 2.3852e-05 89.315998635 1.0 -0.684001365 1.0 -0.684001365 2.3852e-05 89.315998635
200.0 2.5107e-05 89.279998563 1.0 -0.720001437 1.0 -0.720001437 2.5107e-05 89.279998563
210.0 2.6362e-05 89.243998491 1.0 -0.756001509 1.0 -0.756001509 2.6362e-05 89.243998491
220.0 2.7618e-05 89.207998419 1.0 -0.792001581 1.0 -0.792001581 2.7618e-05 89.207998419
230.0 2.8873e-05 89.171998348 1.0 -0.828001652 1.0 -0.828001652 2.8873e-05 89.171998348
240.0 3.0128e-05 89.135998276 1.0 -0.864001724 1.0 -0.864001724 3.0128e-05 89.135998276
250.0 3.1383e-05 89.099998204 1.0 -0.900001796 1.0 -0.900001796 3.1383e-05 89.099998204

Please report back and close this if changing the precision works.
