### ISSUE TITLE
SignalIntegrity APP Issue for Eyediagram Creation

### ISSUE THREAD

**Issue by Foxpuma** [Nubis-Communications/SignalIntegrity#79]
Issue: Eye diagram creation failed if the circuit symbol is created manually. The waveform is using the example waveform: Waveform_CableTxPWf.txt.
However, if the example circuit symbol is used and settings/waveforms are the same as the one created manually, it’s ok to create eye diagram.
[SignalIntegrity APP Issue for Eyediagram Creation.pdf](https://github.com/user-attachments/files/15935554/SignalIntegrity.APP.Issue.for.Eyediagram.Creation.pdf)

**Comment by Foxpuma** [comment]
[App-eyediagram-newV.zip](https://github.com/user-attachments/files/15935676/App-eyediagram-newV.zip)

**Comment by PetePupalaikis** [comment]
Your impulse response length on your simulation is set to 100 ns, and your input waveform is only 100 ns long.  So, when you view the waveforms and turn off all of the others except for Vo1 (which you are using to create the eye diagram), you will find that Vo1 is nothing -- there's no waveform left to compute an eye from.  For your simulation, the impulse response could be set very small, like 1 ns, in which case, the waveform result exists and your eye can be drawn.

Try it and please close this issue if you understand the problem in your setup.
